#
# Copyright (c) 2020 P3TERX
# Modified: Added Docker Buildx cache support
#

name: Aria2 Builder (Cached)

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        PLATFORMS: [amd64]
        include:
        - PLATFORMS: amd64
          BUILDER_IMAGE: debian:12
          BUILD_SCRIPT: aria2-gnu-linux-build-amd64.sh

    steps:

    - name: Install QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Checkout
      uses: actions/checkout@v3

    # ------------------------- CACHE PART -------------------------
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    # ---------------------------------------------------------------

    - name: Build
      env:
        DOCKER_BUILDKIT: 1
        BUILDER_IMAGE: ${{ matrix.BUILDER_IMAGE }}
        BUILD_SCRIPT: ${{ matrix.BUILD_SCRIPT }}
      run: |
        docker buildx build \
          --build-arg BUILDER_IMAGE \
          --build-arg BUILD_SCRIPT \
          --platform=local \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache-new \
          -o ./output .

    - name: Update docker cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Output Error Log
      if: (!cancelled())
      run: grep -iE 'fatal|error|critical|failure|warning' build.log || true

    - name: Check Version
      run: |
        tar xzvf ./output/aria2*.tar.gz
        file aria2c 2>&1 | tee ./output/file-type-${{ matrix.PLATFORMS }}.txt
        ./aria2c -v 2>&1 | tee ./output/version-${{ matrix.PLATFORMS }}.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2-${{ matrix.PLATFORMS }}
        path: output

    - name: Functional Testing
      run: |
        ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht.dat
        ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht6.dat
